#!/usr/bin/env python3
"""Generate ROSTER.md — a compact, machine-readable index of every agent.

Consumed by staffing tooling (e.g. the /staff Claude Code skill) that needs to
match agents to a task without reading ~200 full personality files. Reads the
division set from divisions.json (the source of truth per its _note) and each
agent's frontmatter `name` and `description`.

Usage: scripts/generate-roster-index.py  (from anywhere; paths resolve to repo root)
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROSTER_PATH = REPO_ROOT / "ROSTER.md"

FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def parse_frontmatter(text):
    """Minimal YAML-ish parser: top-level `key: value` string pairs only."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    fields = {}
    for line in match.group(1).splitlines():
        if ":" not in line or line.startswith((" ", "\t", "#")):
            continue
        key, _, value = line.partition(":")
        value = value.strip().strip("'\"")
        if value:
            fields[key.strip()] = value
    return fields


def main():
    divisions = json.loads((REPO_ROOT / "divisions.json").read_text())["divisions"]

    lines = [
        "# Agent Roster Index",
        "",
        "<!-- GENERATED by scripts/generate-roster-index.py — do not edit by hand. -->",
        "",
        "One line per agent: `path` — **Name** — description. Regenerate after",
        "adding or editing agents: `scripts/generate-roster-index.py`.",
        "",
    ]

    total = 0
    skipped = []
    for slug in sorted(divisions):
        entries = []
        for path in sorted((REPO_ROOT / slug).rglob("*.md")):
            if path.name.upper().startswith("README"):
                continue
            fields = parse_frontmatter(path.read_text(encoding="utf-8"))
            if "name" not in fields or "description" not in fields:
                skipped.append(str(path.relative_to(REPO_ROOT)))
                continue
            rel = path.relative_to(REPO_ROOT)
            entries.append(f"- `{rel}` — **{fields['name']}** — {fields['description']}")
        lines.append(f"## {divisions[slug]['label']} ({len(entries)})")
        lines.append("")
        lines.extend(entries)
        lines.append("")
        total += len(entries)

    lines.insert(6, "")
    lines.insert(7, f"**{total} agents across {len(divisions)} divisions.**")
    ROSTER_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {ROSTER_PATH.name}: {total} agents, {len(divisions)} divisions.")
    if skipped:
        print(f"Skipped {len(skipped)} file(s) without name/description frontmatter:",
              file=sys.stderr)
        for s in skipped:
            print(f"  {s}", file=sys.stderr)


if __name__ == "__main__":
    main()
